export const ADD_TODO = "ADD_TODO";
export const ARCHIVE_TODO = "ARCHIVE_TODO";
export const SET_FILTER = "SET_FILTER";
export const TODO_CLICK = "TODO_CLIKC";
export const TODO_DELETE = "TODO_DELETE";
export const ARCHIVE_TODO_DELETE = "ARCHIVE_TODO_DELETE";
export const TODO_MODIFY_REQUEST = "TODO_MODIFY_REQUEST";
export const TODO_MODIFY_CANCEL = "TODO_MODIFY_CANCEL";
export const TODO_MODIFY_SUCCESS = "TODO_MODIFY_SUCCESS";
export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const MOVE_COMMENT = " MOVE_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENTS = "DELETE_COMMENTS";
export const COMMENT_REQUEST_CANCELLED = "COMMENT_REQUEST_CANCELLED";
export const ARCHIVE_COMMENTS_OF_TODO = "ARCHIVE_COMMENTS_OF_TODO";
export const SET_TODO_ERROR = "SET_TODO_ERROR";
export const CANCEL_TODO_ERROR = "CANCEL_TODO_ERROR";
export const SET_COMMENT_MODIFY = "SET_COMMENT_MODIFY";
export const DELETE_A_COMMENT = "DELETE_A_COMMENT";
export const MODIFY_COMMENT = "MODIFY_COMMENT";
export const CANCEL_MODIFY_COMMENT = "CANCEL_MODIFY_COMMENT";
export const TOGGLE_ALL_TODOS = "TOGGLE_ALL_TODOS";
export const DELETE_ALL_COMPLETED_TODOS = "DELETE_ALL_COMPLETED_TODOS";
export const DELETE_ARCHIVE_COMMENTS_OF_TODO =
  "DELETE_ARCHIVE_COMMENTS_OF_TODO";
export const filters_constants = {
  ALL: "ALL",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  TOGGLE_ALL: "TOGGLE_ALL",
  DELETE_COMPLETED: "DELETE_COMPLETED",
  ARCHIVES: "ARCHIVES"
};
export const comment_items = ["Delete", "Modify", "Move to"];

export const ADD_TO_BLOCK_LIST_OF_TODO = "ADD_TO_BLOCK_LIST_OF_TODO";
export const DELETE_TODO_FROM_BLOCKING_ENTRY =
  "DELETE_TODO_FROM_BLOCKING_ENTRY";
export const DELETE_TODO_FROM_BLOCKEDBY_LIST_OF_TODO =
  "DELETE_TODO_FROM_BLOCKEDBY_LIST_OF_TODO";

export const OPENED_TODO_BOARD = "OPENED_TODO_BOARD";
export const CLOSE_TODO_BOARD = "CLOSE_TODO_BOARD";
export const ADD_SUBTASK = "ADD_SUBTASK";
export const UPDATE_SUBTASK = "UPDATE_SUBTASK";
export const DELETE_A_SUBTASK = "DELETE_A_SUBTASK";
export const ARCHIVE_SUBTASKS = "ARCHIVE_SUBTASKS";
export const DELETE_ARCHIVE_SUBTASKS_OF_TODO =
  "DELETE_ARCHIVE_SUBTASKS_OF_TODO";
